# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 12:39
from __future__ import unicode_literals

import ZooApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZooApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='finance',
            field=models.IntegerField(default=0, validators=[ZooApp.models.validate_positive_finance]),
        ),
    ]
